### ISSUE TITLE
DynamicRNNLayer without dropout multi layer will error

### ISSUE THREAD

**Issue by wugh** [tensorlayer/tensorlayer#412]
There is some code error when DynamicRNNLayer with multi layer and without dropout .
code
```
        with tf.variable_scope('rnn') as vs:
            tl.layers.DynamicRNNLayer(
                left_embed,
                n_hidden=self.hidden_size,
                cell_fn=tf.contrib.rnn.BasicLSTMCell,
                n_layer=2
            )
```

trackback
```
Traceback (most recent call last):
  File "/Users/wuguohua/Envs/py3tf/lib/python3.6/site-packages/tensorlayer/layers/recurrent.py", line 1086, in __init__
    self.cell = MultiRNNCell_fn([cell_creator(is_last=i == n_layer - 1) for i in range(n_layer)], state_is_tuple=True)
  File "/Users/wuguohua/Envs/py3tf/lib/python3.6/site-packages/tensorlayer/layers/recurrent.py", line 1086, in <listcomp>
    self.cell = MultiRNNCell_fn([cell_creator(is_last=i == n_layer - 1) for i in range(n_layer)], state_is_tuple=True)
TypeError: <lambda>() got an unexpected keyword argument 'is_last'
```

solution
```
        rnn_creator = lambda: cell_fn(num_units=n_hidden, **cell_init_args)
to
        rnn_creator = lambda is_last: cell_fn(num_units=n_hidden, **cell_init_args)
```

**Comment by zsdonghao** [comment]
@wugh It works well on my side, what is your TensorFlow, TensorLayer version?

**Comment by wugh** [comment]
My version is `tensorlayer (1.8.1)`, and I can found this error from latest code in the master brunch
the file is `recurrent.py`
```
        # Creats the cell function
        # cell_instance_fn=lambda: cell_fn(num_units=n_hidden, **cell_init_args) # HanSheng
        # *** code make error ***
        rnn_creator = lambda: cell_fn(num_units=n_hidden, **cell_init_args)

        # Apply dropout
        if dropout:
            if isinstance(dropout, (tuple, list)):
                in_keep_prob = dropout[0]
                out_keep_prob = dropout[1]
            elif isinstance(dropout, float):
                in_keep_prob, out_keep_prob = dropout, dropout
            else:
                raise Exception("Invalid dropout type (must be a 2-D tuple of " "float)")
            try:  # TF1.0
                DropoutWrapper_fn = tf.contrib.rnn.DropoutWrapper
            except Exception:
                DropoutWrapper_fn = tf.nn.rnn_cell.DropoutWrapper

            # cell_instance_fn1=cell_instance_fn        # HanSheng
            # cell_instance_fn=DropoutWrapper_fn(
            #                     cell_instance_fn1(),
            #                     input_keep_prob=in_keep_prob,
            #                     output_keep_prob=out_keep_prob)
            cell_creator = lambda is_last=True: \
                    DropoutWrapper_fn(rnn_creator(),
                                      input_keep_prob=in_keep_prob,
                                      output_keep_prob=out_keep_prob if is_last else 1.0)
        else:
            cell_creator = rnn_creator
        self.cell = cell_creator()
        # Apply multiple layers
        if n_layer > 1:
            try:
                MultiRNNCell_fn = tf.contrib.rnn.MultiRNNCell
            except Exception:
                MultiRNNCell_fn = tf.nn.rnn_cell.MultiRNNCell

            # cell_instance_fn2=cell_instance_fn # HanSheng
            try:
                # cell_instance_fn=lambda: MultiRNNCell_fn([cell_instance_fn2() for _ in range(n_layer)], state_is_tuple=True) # HanSheng
                self.cell = MultiRNNCell_fn([cell_creator(is_last=i == n_layer - 1) for i in range(n_layer)], state_is_tuple=True)
            except Exception:  # when GRU
                # cell_instance_fn=lambda: MultiRNNCell_fn([cell_instance_fn2() for _ in range(n_layer)]) # HanSheng
                self.cell = MultiRNNCell_fn([cell_creator(is_last=i == n_layer - 1) for i in range(n_layer)])
```

**Comment by nebulaV** [comment]
@wugh This bug has been fixed before. The code snippet you pasted here is the old version. Could you give a go using the latest master version?

**Comment by wugh** [comment]
Thanks @nebulaV , I check the latest code, the error has been fix.

**Comment by wugh** [comment]
@nebulaV The code on pypi is not the latest version.
https://pypi.python.org/pypi/tensorlayer/1.8.1
This version still has error

**Comment by zsdonghao** [comment]
@wugh try 1.8.2
