### ISSUE TITLE
tutorial_cifar10.py crashes 1.8.6rc2

### ISSUE THREAD

**Issue by jeffscott** [tensorlayer/tensorlayer#681]
### Issue Description

- tutorial_cifar10.py produces AttributeError when creating output layer
- When I checkout r1.8.5 it works fine, the bug was introduced after that

### Reproducible Code

- MacOS 10.13.4
- Brew installed python 3.6.5

```
> python tutorial_cifar10.py
2018-06-04 22:25:07.729838: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
[TL] Load or Download cifar10 > data/cifar10
[TL] InputLayer  model/input: (?, 24, 24, 3)
[TL] Conv2d model/cnn1: n_filter:64 filter_size:(5, 5) strides:(1, 1) pad:SAME act:identity
[TL] BatchNormLayer batch1: decay:1.000000 epsilon:0.000010 act:relu is_train:False
[TL] MaxPool2d pool1: filter_size:(3, 3) strides:(2, 2) padding:SAME
[TL] Conv2d model/cnn2: n_filter:64 filter_size:(5, 5) strides:(1, 1) pad:SAME act:identity
[TL] BatchNormLayer batch2: decay:1.000000 epsilon:0.000010 act:relu is_train:False
[TL] MaxPool2d pool2: filter_size:(3, 3) strides:(2, 2) padding:SAME
[TL] FlattenLayer model/flatten: 2304
[TL] DenseLayer  d1relu: 384 relu
[TL] DenseLayer  d2relu: 192 relu
Traceback (most recent call last):
  File "tutorial_cifar10.py", line 118, in <module>
    network, cost, _ = model_batch_norm(x, y_, False, is_train=True)
  File "tutorial_cifar10.py", line 66, in model_batch_norm
    net = DenseLayer(net, 10, act=None, W_init=W_init2, name='output')
  File "/Users/jscott/tensorflow/tensorenv/lib/python3.6/site-packages/tensorlayer/deprecation.py", line 24, in wrapper
    return f(*args, **kwargs)
  File "/Users/jscott/tensorflow/tensorenv/lib/python3.6/site-packages/tensorlayer/layers/core.py", line 963, in __init__
    logging.info("DenseLayer  %s: %d %s" % (name, n_units, act.__name__))
AttributeError: 'NoneType' object has no attribute '__name__'
```

```
> git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

```
> git log
commit 701d4d3c4681810a48a122cff3d11f8b2dd7af78 (HEAD -> master, tag: 1.8.6rc2, origin/master, origin/HEAD)
```

**Checkout a previous release**
``` 
example > git checkout tags/1.8.5
HEAD is now at 74a59ce release 1.8.5 (#559)
example> python tutorial_cifar10.py
....
[TL] FlattenLayer model/flatten: 2304
[TL] DenseLayer  d1relu: 384 relu
[TL] DenseLayer  d2relu: 192 relu
[TL] DenseLayer  output: 10 identity #Crash was here
[TL]   [*] geting variables with relu/W
...
```

Just in case:

- Virtual Environment
```
(tensorenv) jscott@jscott-05214:example > pip freeze
absl-py==0.2.2
appnope==0.1.0
astor==0.6.2
backcall==0.1.0
bleach==1.5.0
cycler==0.10.0
decorator==4.3.0
gast==0.2.0
grpcio==1.12.0
html5lib==0.9999999
imageio==2.3.0
ipykernel==4.8.2
ipython==6.4.0
ipython-genutils==0.2.0
jedi==0.12.0
jupyter-client==5.2.3
jupyter-core==4.4.0
kiwisolver==1.0.1
Markdown==2.6.11
matplotlib==2.2.2
networkx==2.1
numpy==1.14.3
parso==0.2.1
pexpect==4.6.0
pickleshare==0.7.4
Pillow==5.1.0
progressbar2==3.37.1
prompt-toolkit==1.0.15
protobuf==3.5.2.post1
ptyprocess==0.5.2
Pygments==2.2.0
pyparsing==2.2.0
python-dateutil==2.7.3
python-utils==2.3.0
pytz==2018.4
PyWavelets==0.5.2
pyzmq==17.0.0
scikit-image==0.13.1
scipy==1.1.0
simplegeneric==0.8.1
six==1.11.0
tensorboard==1.8.0
tensorflow==1.8.0
tensorlayer==1.8.5
termcolor==1.1.0
tornado==5.0.2
traitlets==4.3.2
wcwidth==0.1.7
Werkzeug==0.14.1
```

**Comment by DEKHTIARJonathan** [comment]
We did some heavy changes recently and refactoring. I'm not surprised some bug shows up.
I will correct this one today.

That's actually the reason why we released a `release candidate` and not a stable release ;)

Thanks for trying and reporting this issue ;)

**Comment by jeffscott** [comment]
Got it, thanks Jonathan.
