### ISSUE TITLE
docker import error

### ISSUE THREAD

**Issue by fangde** [tensorlayer/tensorlayer#733]
### Issue Description

I'm using tensorlayer gpu docker, 
it throw out exception due to the model availaibity.

### Reproducible Code

docker run -it --runtime=nvidia tensorlayer/tensorlayer:latest-gpu-py2 bash

```python
# ======================================================== #
###### THIS CODE IS AN EXAMPLE, REPLACE WITH YOUR OWN ######
# ======================================================== #

import tensorflow as tf
import tensorlayer as tl
```

error

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorlayer/__init__.py", line 34, in <module>
    from . import files
  File "/usr/local/lib/python2.7/dist-packages/tensorlayer/files/__init__.py", line 12, in <module>
    from .dataset_loaders.celebA_dataset import *
  File "/usr/local/lib/python2.7/dist-packages/tensorlayer/files/dataset_loaders/__init__.py", line 4, in <module>
    from .celebA_dataset import *
  File "/usr/local/lib/python2.7/dist-packages/tensorlayer/files/dataset_loaders/celebA_dataset.py", line 10, in <module>
    from tensorlayer.files.utils import download_file_from_google_drive
  File "/usr/local/lib/python2.7/dist-packages/tensorlayer/files/utils.py", line 31, in <module>
    import matplotlib.pyplot as plt
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/__init__.py", line 62, in pylab_setup
    [backend_name], 0)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_tkagg.py", line 4, in <module>
    from . import tkagg  # Paint image to Tk photo blitter extension.
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/tkagg.py", line 5, in <module>
    from six.moves import tkinter as Tk
  File "/usr/local/lib/python2.7/dist-packages/six.py", line 203, in load_module
    mod = mod._resolve()
  File "/usr/local/lib/python2.7/dist-packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/usr/local/lib/python2.7/dist-packages/six.py", line 82, in _import_module
    __import__(name)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 42, in <module>
    raise ImportError, str(msg) + ', please install the python-tk package'
ImportError: No module named _tkinter, please install the python-tk package

**Comment by fangde** [comment]
similar issue with python-3
Traceback (most recent call last):
  File "/usr/lib/python3.5/tkinter/__init__.py", line 36, in <module>
    import _tkinter
ImportError: No module named '_tkinter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/tensorlayer/__init__.py", line 34, in <module>
    from . import files
  File "/usr/local/lib/python3.5/dist-packages/tensorlayer/files/__init__.py", line 12, in <module>
    from .dataset_loaders.celebA_dataset import *
  File "/usr/local/lib/python3.5/dist-packages/tensorlayer/files/dataset_loaders/__init__.py", line 4, in <module>
    from .celebA_dataset import *
  File "/usr/local/lib/python3.5/dist-packages/tensorlayer/files/dataset_loaders/celebA_dataset.py", line 10, in <module>
    from tensorlayer.files.utils import download_file_from_google_drive
  File "/usr/local/lib/python3.5/dist-packages/tensorlayer/files/utils.py", line 31, in <module>
    import matplotlib.pyplot as plt
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/backends/__init__.py", line 62, in pylab_setup
    [backend_name], 0)
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/backends/backend_tkagg.py", line 4, in <module>
    from . import tkagg  # Paint image to Tk photo blitter extension.
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/backends/tkagg.py", line 5, in <module>
    from six.moves import tkinter as Tk
  File "/usr/local/lib/python3.5/dist-packages/six.py", line 92, in __get__
    result = self._resolve()
  File "/usr/local/lib/python3.5/dist-packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/usr/local/lib/python3.5/dist-packages/six.py", line 82, in _import_module
    __import__(name)
  File "/usr/lib/python3.5/tkinter/__init__.py", line 38, in <module>
    raise ImportError(str(msg) + ', please install the python3-tk package')
ImportError: No module named '_tkinter', please install the python3-tk package

**Comment by fangde** [comment]
@DEKHTIARJonathan  any suggestion to fix that?
the error occurs every time import tl on dockers

**Comment by fangde** [comment]
I had to manu do sudo install python-tk
shall we add this in the docker file?

**Comment by DEKHTIARJonathan** [comment]
It seems like the library matplotlib is importing python-tk right?

I need to bring a few fixes to the Docker file 👍. I'm gonna open a PR this weekend.

How do you explain that python-tk is missing on Docker and not in native Docker?
