### ISSUE TITLE
[Solved] Error: import tensorlayer

### ISSUE THREAD

**Issue by zeyuanchen23** [tensorlayer/tensorlayer#947]
Hi, 

I have met an import error and solved it. Just wanna share it here in case someone needs it. Below is the error message. It is because libsm6 libxext6 are not installed. This issue can be solved by 

`apt update && apt install -y libsm6 libxext6`

on Ubuntu 16.04

Thanks.

`>>> import tensorlayer`
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python2.7/site-packages/tensorlayer/__init__.py", line 46, in <module>
    from tensorlayer import files
  File "/opt/conda/lib/python2.7/site-packages/tensorlayer/files/__init__.py", line 12, in <module>
    from .dataset_loaders.celebA_dataset import *
  File "/opt/conda/lib/python2.7/site-packages/tensorlayer/files/dataset_loaders/__init__.py", line 4, in <module>
    from .celebA_dataset import *
  File "/opt/conda/lib/python2.7/site-packages/tensorlayer/files/dataset_loaders/celebA_dataset.py", line 10, in <module>
    from tensorlayer.files.utils import download_file_from_google_drive
  File "/opt/conda/lib/python2.7/site-packages/tensorlayer/files/utils.py", line 37, in <module>
    import matplotlib.pyplot as plt
  File "/opt/conda/lib/python2.7/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/opt/conda/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 63, in pylab_setup
    [backend_name], 0)
  File "/opt/conda/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 4, in <module>
    from . import tkagg  # Paint image to Tk photo blitter extension.
  File "/opt/conda/lib/python2.7/site-packages/matplotlib/backends/tkagg.py", line 5, in <module>
    from six.moves import tkinter as Tk
  File "/opt/conda/lib/python2.7/site-packages/six.py", line 203, in load_module
    mod = mod._resolve()
  File "/opt/conda/lib/python2.7/site-packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/opt/conda/lib/python2.7/site-packages/six.py", line 82, in _import_module
    __import__(name)
  File "/opt/conda/lib/python2.7/lib-tk/Tkinter.py", line 39, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ImportError: libX11.so.6: cannot open shared object file: No such file or directory`

**Comment by zsdonghao** [comment]
feel free to reopen if you want to discuss.

we just release 2.0.0 version, matplotlib is removed
